name: contacts
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-312.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  color: "#2F39E0"
  image: assets/images/splash.png
  branding: assets/images/branding.png
  branding_mode: bottom

  color_dark: "#2F39E0"
  image_dark: assets/images/splash.png
  branding_dark: assets/images/branding.png
  
  android_12:
    color: "#2F39E0"
    image: assets/images/android12splash.png
    branding: assets/images/branding.png

    color_dark: "#2F39E0"
    image_dark: assets/images/android12splash.png

  android_screen_orientation: sensorPortrait

flutter:

  uses-material-design: true
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
