name: contacts
description: ADEV Ventures Technical Assessment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-312.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  flame: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/